[server]
maxUploadSize = 500
enableXsrfProtection = false
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = true
fastReruns = true
